In [34]:
import geopandas as gpd
from shapely import wkt
import numpy as np

In [35]:
import json

In [36]:
gdf = gpd.read_file('PoliceBeatsClean1.json')

In [37]:
gdf["coordinates"] = gdf.geometry.centroid

/var/folders/y4/t37jhmcx5fv_6z2p5_3s7py00000gn/T/ipykernel_4169/1269880621.py:1: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf["coordinates"] = gdf.geometry.centroid

In [39]:
gdf["lat"] = gdf.coordinates.y
gdf["lng"] = gdf.coordinates.x

In [40]:
gdf = gdf[['acres', 'name', 'shape_area', 'cp_beat', 'agency', 'pol_dist',
       'response', 'id', 'pol_beat', 'fullname', 'flag', 'ruleid_1', 'message',
       'sourcethm', 'action', 'pol_sect', 'shape_len', 'lng', 'lat', 'geometry']]

In [41]:
gdf

,acres,name,shape_area,cp_beat,agency,pol_dist,response,id,pol_beat,fullname,flag,ruleid_1,message,sourcethm,action,pol_sect,shape_len,lng,lat,geometry
0,214.241,03X,10456735.4319,3X,OP,1,,342,3,,0,0,0,Pb,P,1,13802.4944688,-122.266745,37.798540,"MULTIPOLYGON (((-122.26220 37.79220, -122.2623..."
1,281.682,04X,12977459.8553,4X,OP,1,,48,4,,0,0,0,Pb,P,1,15822.3748516,-122.268629,37.807297,"MULTIPOLYGON (((-122.26160 37.81068, -122.2615..."
2,310.616,06X,13540956.6952,6X,OP,1,,2546,6,,0,0,0,Pb,P,1,16751.3426296,-122.273184,37.823714,"MULTIPOLYGON (((-122.27771 37.83124, -122.2775..."
3,1866.395,05Y,79093765.2073,5Y,OP,1,,2628,5,,0,0,0,Pb,P,1,50618.5643586,-122.324286,37.816057,"MULTIPOLYGON (((-122.28990 37.81514, -122.2903..."
4,225.218,05X,9938690.01843,5X,OP,1,,8,5,,0,0,0,Pb,P,1,13676.9039797,-122.283134,37.812159,"MULTIPOLYGON (((-122.27833 37.80777, -122.2786..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,282.393,27X,12302064.7024,27X,OP,4,,3,27,,0,0,0,Pb,P,3,15571.8207512,-122.204279,37.775399,"MULTIPOLYGON (((-122.19457 37.77353, -122.1949..."
110,549.377,29X,23930611.5377,29X,OP,5,,19,29,,0,0,0,Pb,P,3,24525.214859,-122.178579,37.774332,"MULTIPOLYGON (((-122.16873 37.77837, -122.1678..."
111,295.576,31Z,12875312.438,31Z,OP,5,,42,31,,0,0,0,Pb,P,3,20223.3815168,-122.178933,37.730681,"MULTIPOLYGON (((-122.17057 37.73202, -122.1705..."
112,13616.028,31X,596679125.599,31X,OP,5,,46,31,,0,0,0,Pb,P,3,144658.220777,-122.224497,37.693145,"MULTIPOLYGON (((-122.19533 37.75215, -122.1960..."
113,2689.367,35Y,119367348.016,35Y,OP,5,,55,35,,0,0,0,Pb,P,3,52001.4597015,-122.133554,37.751274,"MULTIPOLYGON (((-122.14055 37.77095, -122.1400..."

In [42]:
gdf.to_file("PoliceBeatsClean.json", driver="GeoJSON")